variables:
    IMAGE_NAME: janortop5/laravel-app
    IMAGE_TAG: latest

build_image:
    stage: build
    image: docker:23.0.1-cli
    services:
        - docker:23.0.1-dind
    variables:
        DOCKER_TLS_CERTDIR: "/certs"
    before_script:
        - cd laravel-app
        - cp $ENV_FILE .env.example
        - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
    script: 
        - docker build -t $IMAGE_NAME:$IMAGE_TAG .
        - docker push $IMAGE_NAME:$IMAGE_TAG

