variables:
    IMAGE_NAME: janortop5/laravel-app
    IMAGE_TAG: latest


stages:
    - "test"
    - "build"
    - "deploy"

run_tests:
    stage: test
    variables:
        MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
        MYSQL_DATABASE: $MYSQL_DATABASE
    image: ubuntu:22.10
    services:
        - name: mysql:5.7
          alias: db
    before_script:
        - cd laravel-app
        - cp $ENV_FILE .env.example
        - chmod +x laravel_test.sh
    script:
        - ./laravel_test.sh

build_image:
    stage: build
    image: docker:23.0.1-cli
    services:
        - docker:23.0.1-dind
    variables:
        DOCKER_TLS_CERTDIR: "/certs"
    before_script:
        - cd laravel-app
        - cp $ENV_FILE .env.example
        - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
    script: 
        - docker build -t $IMAGE_NAME:$IMAGE_TAG .
        - docker push $IMAGE_NAME:$IMAGE_TAG

test_aws_connection:
    before_script:
        - chmod +x job.sh
    script: 
        - ./job.sh
        - cp $AWS_CONFIG ~/.aws/config 
        - cp $AWS_CREDENTIALS ~/.aws/credentials 
        - aws configure || true 
